### ISSUE TITLE
pdf-sanitize error

### ISSUE THREAD

**Issue by martinlindhe** [micahflee/pdf-redact-tools#5]
Testing the scripts on Debian sid.

See my previous bug report about build_deb.sh, i am testing from the git checkout.

$ ./pdf-sanitize ~/e-books/First\ Aid\ Made\ Easy.pdf 
Traceback (most recent call last):
  File "./pdf-sanitize", line 26, in <module>
    subprocess.call(['pdf-explode', input_filename])
  File "/usr/lib/python2.7/subprocess.py", line 522, in call
    return Popen(*popenargs, **kwargs).wait()
  File "/usr/lib/python2.7/subprocess.py", line 710, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1327, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory

**Comment by micahflee** [comment]
Thanks for reporting this! Sorry I've completely ignored it for so long. I can reproduce this, and am working on a fix.

**Comment by micahflee** [comment]
Fixed!

**Comment by martinlindhe** [comment]
thanks! will retry when i get some time
